PACMAN_PKGS=(
   btop
   rbw
   fastfetch
   fzf
   curl
   vlc
   gimp
   swaync
   pipewire
   rofi
   dolphin
   libreoffice-fresh
   zip
   unzip
   cliphist
   wireplumber
   pipewire-pulse
   wget
   neovim
   starship
   git
   base-devel
   hyprland
   waybar
   xdg-desktop-portal-hyprland
   hyprpolkitagent
   ttf-cascadia-mono-nerd 
   ttf-rubik-vf
   nvidia-open
   networkmanager
   blueman
   network-manager-applet
   wezterm
   steam
   wl-clip-persist
   yazi
   prismlauncher
)

AUR_PKGS=(
   hyprshot
   hyprpaper
   zen-browser-bin
   wiremix-git
   vesktop
   spicetify-cli
)


