PACMAN_PKGS=(
   btop
   bitwarden-cli
   fastfetch
   fzf
   curl
   vlc
   gimp
   swaync
   pipewire
   rofi
   dolphin
   libreoffice-fresh
   zip
   unzip
   cliphist
   wireplumber
   pipewire-pulse
   wget
   neovim
   starship
   git
   base-devel
   hyprland
   waybar
   xdg-desktop-portal-hyprland
   hyprpolkitagent
   ttf-cascadia-mono-nerd 
   ttf-rubik-vf
   nvidia-open
   networkmanager
   blueman
   network-manager-applet
   ncspot
)

AUR_PKGS=(
   hyprshot
   swww
   prismlauncher
   zen-browser-bin
   steam
   wezterm
   yazi
   wiremix-git
   wl-clip-persist 
   vesktop
)


